database:
  host: "localhost"
  port: 336
  username: "user"
  password: "password"
  name: "mydatabase"

agent:
  ai_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  ai_name: "qwen3.5-plus"
  ai_api_key: "xxxxxxxxxxxxxxxxxxx"